sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: p88nT7YAdXl9ngLfXZRG965HedSfDhfKQFvyrrtoAHvMjVLDrbTRwpbbjDm1ggL3wYq1fK0dJCryYQfeIQnK5Pogqpb1AyYoW1x4PEqRlFiWAgGjUt2BkAWrB4rJkitNhNK6llzfGVYSTUfBeSJqZfKGxGnWq1IZWVj0tyBy67aVfXz/dGcdosg6v00Zn5Sy5n+X4r3eoppz+dYjcQLTaV5IzH41FSs8vP4MezFDJcSy0ozJcWUQhiVnz2ugm8zwl+x4gc/O1E/V28oQ4c/NlkYwrMJum0bzCZZv5ai3e1g8Os9hnQKgYFMuc/JZy6rFI64HOJ7+mgCWy9wqR544ctqCF/7HGEnWAMBDWcGLmc+81b9aC2PNXgdVLt4j7mqeLOUK1EMBU32ndj101USjFdPqpF2kdnXV0T8+nAv03IG+SuNQLCV/+n3RxnqSs4VhDXvwM468nx6NHuvJiL2qcfQ1EqHz0er9qIDdNaNVFjmGy+4Sd++fR4vAyjsMj+9aD+sxi6m9sarDqpgLpADN396Ch3sNE8jaX8zlvdtTaXrlSY7RdP35fXtEN3nUSFPwEtM8D2bhCPVtBsuujw+UveSFNpKCGi9VmaLjs0mBiHNfCDieN01oBwxixiybFN1WNiX+N5bHc24AXhF1zAP8olnpYN9aXWTZBrrAh+4+ako=}, {secure: SE7O2O7CUsOr11vbX1VEjgOVgJ7IIHsiLm5rejGvY8LY6D6Matwd3oP6lIGntUXUK5GO3udU2bKlrtlifqei2zcDnkPzshZH51afx/GEYksBmRn2TFSPgvngkMjrPzjUbr7CviHEeY8Rws2iMC6x0ZeiozoRnq6b9uP4La+dHvcUrO2makws3F0Mt7rr9Y+08naV+2J5rvbQsMjdRZ2DmZDh7VP7RAhwHlaFNQwAWE6uWXGmE3dKf6Cs6RX95fPGOdqvrqwYLWVY69AXU78XyX5REShOa7zpuuo3iwXtcNNZE6hX84ZC6W7DAOK5S+SWtmMcrSRCOiEn8ZxCE7H0Q7OMbU9YQEzTa+CzRYSx5eWr/7CX0bvA1METKr02Ukw1CBiw30ukOZZLcEoYV8dLDLsURmIPjKeaql/+BMfN1VNQQZ1gK63c/LUA06iC3QkWk+5uLkmwhr4PyDEsRal6NjkMelDcLZ9nekbIqTiPi1tExf3oKdBgN8+5EpLcJBAR6auvCVc9XtnLfeoc8RWj6g3TIY6O++KM3UKdiKizoGEdlmbuwV77mDMIF2aOvYJq4cj3qE/Fim2dRlvD9OLUMnI8wAkG/K2A64c9jOWeJOGxduNmzCFcAYzqsoFm84U6ggdtZOzi8Sjn5dBvQu2Ma7zhQQ3ov4Czytin7CUF5Pw=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
